version: '3.8'

services:
  django-server:
    container_name: django-server-container
    build: .
    image: django-server:latest
    platform: linux/amd64
    command: >
      sh -c "
      python manage.py runserver 0.0.0.0:8000 &
      python diary/consumer/create_diary_consumer.py &
      python diary/consumer/re_create_diary_consumer.py
      "
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  celery-worker:
    container_name: celery_worker_container
    build: .
    image: celery-worker:latest
    platform: linux/amd64
    command: celery -A config worker --loglevel=info --pool=threads --concurrency=10
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - redis

volumes:
  redis_data:
