spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/dev
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
