security:
  oauth2:
    client:
      registration:
        kakao:
          client-id: 1093843
          client-secret: ${KAKAO_CLIENT_SECRET}
          rest-api-key: ${KAKAO_REST_API_KEY}
          scope: profile_nickname, profile_image, account_email
          client-name: Kakao
          client-authentication-method: client_secret_post # kakao는 client_secret_basic이 아닌 client_secret_post
          authorization-grant-type: authorization_code
      provider:
        kakao:
          authorization-uri: https://kauth.kakao.com/oauth/authorize
          token-uri: https://kauth.kakao.com/oauth/token
          user-info-uri: https://kapi.kakao.com/v2/user/me
          user-name-attribute: id
          user-info-authentication-method: header

jwt:
  secret: ${JWT_SECRET}
  access-token-expire-time: 3600000  # 1시간
  refresh-token-expire-time: 5184000000 # 60일
