name: EC2로 배포

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      profile: ${{ secrets.PROFILE }}
    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: JDK 17버전 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: 테스트 및 빌드하기
        run: |
          cd server/Spring
          rm -rf server/Spring/src/main/resources
          echo "${{ secrets.APPLICATION_YML }}" > ./src/main/resources/application.yml
          echo "${{ secrets.KAFKA_YML }}" > ./src/main/resources/application-kafka.yml
          echo "${{ secrets.OAUTH_YML }}" > ./src/main/resources/application-oauth.yml
          echo "${{ secrets.AWS_YML }}" > ./src/main/resources/application-aws.yml
          ./gradlew clean build -Dspring.profiles.active=${{ env.profile }}

      - name: 빌드된 파일 이름 변경하기
        run: mv server/Spring/build/libs/*SNAPSHOT.jar ./project.jar

      - name: SCP로 EC2에 빌드된 파일 전송하기
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: project.jar
          target: /home/ubuntu/Diarist/tobe

      - name: SSH로 EC2에 접속하기
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
             rm -rf /home/ubuntu/Diarist/current
             mkdir /home/ubuntu/Diarist/current
             mv /home/ubuntu/Diarist/tobe/project.jar /home/ubuntu/Diarist/current/project.jar
             cd /home/ubuntu/Diarist/current
             sudo fuser -k -n tcp 8080 || true
             nohup java -jar project.jar > ./output.log 2>&1 & 
             rm -rf /home/ubuntu/Diarist/tobe